server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: create  #?? table? ??? ?? ?? ?? ???! cf) update? ??? ???
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    username: gangnam
    password: gangnam
    url: jdbc:mysql://localhost:3306/login
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  key: tlzbflxldjvmffpzldptus
  time: 86400000  #??? ???? ??